language: node_js
branches:
  only:
    - master
before_script:
  - npm run test
  - npm run lint
script:
  - npm run build
after_script:
  - npm run test:coverage
  - npm run test:coverage:report
after_success:
  - npm run semantic-release